apiVersion: launchpad.mirantis.com/mke/v1.3
kind: mke
metadata:
  name: my-mke-cluster
spec:
  hosts:
  - address: 3.239.191.77
    role: manager
    ssh:
      keyPath: /home/devops/.ssh/id_rsa
      user: devops
      port: 22
    privateInterface: eth0
  - address: 3.226.236.199
    role: worker
    ssh:
      keyPath: /home/devops/.ssh/id_rsa
      user: devops
      port: 22
    privateInterface: eth0
  mke:
    version:3.3.7
    installFlags:
    - --adminUsername: admin
    - --adminPassword: P@ssw0rd_123
    - --default-node-orchestrator=kubernetes
    - --pod-cidr 10.0.0.0/16
  mcr:
    version: 19.03.14
  cluster:
    prune: false    