apiVersion: launchpad.mirantis.com/mke/v1.1
kind: mke
metadata:
  name: my-mke-cluster
spec:
  hosts:
  - address: 44.197.187.203
    role: manager
    ssh:
      keyPath: /home/devops/.ssh/id_rsa
      user: devops
      port: 22
    privateInterface: eth0
  - address: 3.239.237.135
    role: worker
    ssh:
      keyPath: /home/devops/.ssh/id_rsa
      user: devops
      port: 22
    privateInterface: eth0
  mke:
    version: 3.3.7
    adminUsername: admin
    adminPassword: p@ssw0rd_123
    installFlags:
    - --default-node-orchestrator=kubernetes
    - --pod-cidr 10.0.0.0/16
    - --force-minimums
  engine:
    version: 20.10.0